export const DATA = [
  {
    id: 1,
    title: 'Поиск',
    imgUrl: './image/search-of-book.jpg',
    href: 'https://truth-autumn-syringa.glitch.me',
    alt: 'Проект по поиску книг',
  },
  {
    id: 2,
    title: 'Планировщик',
    imgUrl: './image/plan.jpg',
    href: 'https://smart-ancient-honeysuckle.glitch.me',
    alt: 'Планировщик дел',
  },
  {
    id: 3,
    title: 'Фотоальбом',
    imgUrl: './image/calculate.jpg',
    href: 'https://verdant-petal-oval.glitch.me',
    alt: 'Альбом с фотографиями',
  },
  {
    id: 4,
    title: 'Воспоминания',
    imgUrl: './image/remembers.jpg',
    href: 'https://tricky-short-link.glitch.me',
    alt: 'Cчастливые воспоминания',
  },
  {
    id: 5,
    title: 'Таймер',
    imgUrl: './image/timer.jpg',
    href: 'https://equatorial-admitted-crabapple.glitch.me',
    alt: 'Таймер',
  },
  {
    id: 6,
    title: 'Калькулятор',
    imgUrl: './image/calculate.jpg',
    href: 'https://sphenoid-delightful-moustache.glitch.me',
    alt: 'Расчет времени до достижения цели',
  },
  {
    id: 7,
    title: 'Мотиватор',
    imgUrl: './image/calculate.jpg',
    href: 'https://pointed-evening-feverfew.glitch.me',
    alt: 'Приложение по рандомному отображению жезнеутверждающих фраз',
  },
  {
    id: 8,
    title: 'викторина',
    imgUrl: './image/calculate.jpg',
    href: 'https://silken-gray-fiction.glitch.me',
    alt: 'Новогодняя кулинарная викторина',
  },
  {
    id: 9,
    title: 'Прогноз',
    imgUrl: './image/calculate.jpg',
    href: 'https://warm-future-cyclamen.glitch.me',
    alt: 'Приложение о погоде',
  },
  {
    id: 10,
    title: 'Игра',
    imgUrl: './image/calculate.jpg',
    href: 'https://foul-diamond-walk.glitch.me',
    alt: 'Игра - поймай юркий кружочек',
  }
];
